/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness Probe
         * @description Returns immediate 200 OK to confirm the web process is alive and accepting connections.
         */
        get: operations["liveness_check_api_v1_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness Probe
         * @description Validates database connectivity, latency, and core system health.
         */
        get: operations["readiness_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new platform user
         * @description Registers a new student, instructor, or admin user.
         *     Enforces email uniqueness and bcrypt password hashing.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate user and issue JWT token
         * @description Authenticates user credentials and returns a signed JWT access token.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current authenticated user profile
         * @description Returns the authenticated user profile for the caller.
         */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/instructor-only": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Protected instructor diagnostic route
         * @description Diagnostic endpoint verifying Server-Side Role-Based Access Control (PRD Constraint #6).
         */
        get: operations["instructor_only_check_api_v1_auth_instructor_only_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learning-state/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute a verified learning state transition
         * @description Validates and executes an atomic state transition in the Student Learning State Machine.
         *     Records an immutable audit log entry with structured evidence (PRD §13, FR-001, FR-025).
         */
        post: operations["transition_learning_state_api_v1_learning_state_transition_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learning-state/topic/{topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current student state for a topic
         * @description Fetches the current learning state for a specific student, exam, and topic.
         */
        get: operations["get_topic_state_api_v1_learning_state_topic__topic_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learning-state/topic/{topic_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get audit log history for a topic
         * @description Retrieves the complete immutable audit trail for a topic (PRD FR-025, NFR-008).
         */
        get: operations["get_topic_history_api_v1_learning_state_topic__topic_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learning-state/exam/{exam_template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get student exam learning progress summary
         * @description Fetches aggregate progress metrics and all topic states for an exam.
         */
        get: operations["get_exam_summary_api_v1_learning_state_exam__exam_template_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exam-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all active exam templates
         * @description Returns the catalog of all available examination templates with subject and topic counts (PRD §5.1, FR-002).
         */
        get: operations["list_exam_templates_api_v1_exam_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exam-templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get exam template by ID or code
         * @description Retrieves metadata and configuration for a specific examination template.
         */
        get: operations["get_exam_template_api_v1_exam_templates__template_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete an exam template and its syllabus (Admin only)
         * @description Permanently removes an exam template and cascades deletions to all associated subjects, topics, and objectives.
         */
        delete: operations["delete_exam_template_api_v1_exam_templates__template_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exam-templates/{template_id}/syllabus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get complete hierarchical syllabus tree for an exam
         * @description Returns the nested syllabus tree (Subjects -> Topics -> Subtopics & Learning Objectives & Prerequisites)
         *     for rendering in the syllabus explorer UI.
         */
        get: operations["get_syllabus_tree_api_v1_exam_templates__template_id__syllabus_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exam-templates/topics/{topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get topic details with objectives and prerequisites
         * @description Retrieves topic information including subtopics, LaTeX formulas, Bloom levels, and prerequisite links.
         */
        get: operations["get_topic_detail_api_v1_exam_templates_topics__topic_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exam-templates/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import complete nested curriculum blueprint (Admin/Instructor only)
         * @description Parses and persists a full nested curriculum blueprint (Exam -> Subjects -> Topics -> Objectives & Prerequisites)
         *     in a single atomic database transaction.
         */
        post: operations["import_exam_blueprint_api_v1_exam_templates_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exam-templates/{template_id}/dag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get complete topic dependency graph with depth levels and connectivity
         * @description Returns the visual Directed Acyclic Graph (DAG) for an exam template including node depth levels,
         *     in-degrees, out-degrees, and mandatory prerequisite edges for DAG visualization.
         */
        get: operations["get_exam_dag_api_v1_exam_templates__template_id__dag_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exam-templates/{template_id}/learning-path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get canonical topologically sorted recommended learning sequence
         * @description Computes a linear topological sequence of topics guaranteeing that all prerequisites are completed
         *     prior to dependent topics.
         */
        get: operations["get_learning_path_api_v1_exam_templates__template_id__learning_path_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exam-templates/{template_id}/unlocked-topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get unlocked vs locked topic statuses for a student
         * @description Evaluates which topics are currently LOCKED, UNLOCKED, or MASTERED for the given student
         *     based on their recorded learning state history.
         */
        get: operations["get_unlocked_topics_api_v1_exam_templates__template_id__unlocked_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exam-templates/{template_id}/topics/{topic_id}/blockers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get ancestral prerequisite blockers for a struggling student on a topic
         * @description Performs reverse graph reachability analysis to extract all unmastered ancestral prerequisites
         *     preventing a student from mastering the target topic.
         */
        get: operations["get_topic_prerequisite_blockers_api_v1_exam_templates__template_id__topics__topic_id__blockers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exam-templates/{template_id}/validate-dag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Audit curriculum DAG integrity and detect circular dependencies (Admin/Instructor)
         * @description Audits the exam template's topic prerequisite graph for cycles, connectivity, and depth levels.
         */
        post: operations["validate_exam_dag_api_v1_exam_templates__template_id__validate_dag_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BlockerNodeResponse */
        BlockerNodeResponse: {
            /** Topic Id */
            topic_id: string;
            /** Title */
            title: string;
            /** Difficulty */
            difficulty: string;
            /** Level */
            level: number;
            /** Current State */
            current_state: string;
            /** Is Direct Prerequisite */
            is_direct_prerequisite: boolean;
        };
        /**
         * BloomLevel
         * @enum {string}
         */
        BloomLevel: "Remember" | "Understand" | "Apply" | "Analyze" | "Evaluate" | "Create";
        /** DAGEdgeResponse */
        DAGEdgeResponse: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /**
             * Is Mandatory
             * @default true
             */
            is_mandatory: boolean;
        };
        /** DAGGraphResponse */
        DAGGraphResponse: {
            /** Exam Template Id */
            exam_template_id: string;
            /** Exam Title */
            exam_title: string;
            /** Is Acyclic */
            is_acyclic: boolean;
            /** Cycle Path */
            cycle_path?: string[] | null;
            /** Total Nodes */
            total_nodes: number;
            /** Total Edges */
            total_edges: number;
            /**
             * Root Topic Ids
             * @default []
             */
            root_topic_ids: string[];
            /**
             * Terminal Topic Ids
             * @default []
             */
            terminal_topic_ids: string[];
            /**
             * Nodes
             * @default []
             */
            nodes: components["schemas"]["DAGNodeResponse"][];
            /**
             * Edges
             * @default []
             */
            edges: components["schemas"]["DAGEdgeResponse"][];
        };
        /** DAGNodeResponse */
        DAGNodeResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Subject Id */
            subject_id: string;
            /** Difficulty */
            difficulty: string;
            /** Estimated Hours */
            estimated_hours: number;
            /** Importance Weight */
            importance_weight: number;
            /** In Degree */
            in_degree: number;
            /** Out Degree */
            out_degree: number;
            /** Level */
            level: number;
            /**
             * Prerequisite Ids
             * @default []
             */
            prerequisite_ids: string[];
            /**
             * Dependent Ids
             * @default []
             */
            dependent_ids: string[];
        };
        /** DAGValidationResponse */
        DAGValidationResponse: {
            /** Exam Template Id */
            exam_template_id: string;
            /** Exam Title */
            exam_title: string;
            /** Is Valid */
            is_valid: boolean;
            /** Has Cycles */
            has_cycles: boolean;
            /** Cycle Path */
            cycle_path?: string[] | null;
            /** Total Topics */
            total_topics: number;
            /** Total Prerequisite Edges */
            total_prerequisite_edges: number;
            /**
             * Root Topic Ids
             * @default []
             */
            root_topic_ids: string[];
            /**
             * Terminal Topic Ids
             * @default []
             */
            terminal_topic_ids: string[];
            /**
             * Max Depth Level
             * @default 0
             */
            max_depth_level: number;
        };
        /**
         * ExamBoard
         * @enum {string}
         */
        ExamBoard: "Cambridge International" | "College Board" | "AQA" | "IB" | "AAMC";
        /**
         * ExamLearningSummaryResponse
         * @description Overview of all topic states for a student in a specific exam.
         */
        ExamLearningSummaryResponse: {
            /** Student Id */
            student_id: string;
            /** Exam Template Id */
            exam_template_id: string;
            /** Total Topics */
            total_topics: number;
            /** Mastered Count */
            mastered_count: number;
            /** In Progress Count */
            in_progress_count: number;
            /** Topic States */
            topic_states: components["schemas"]["StudentLearningStateResponse"][];
        };
        /** ExamTemplateImportSchema */
        ExamTemplateImportSchema: {
            /** Title */
            title: string;
            /** Code */
            code: string;
            /** @default Cambridge International */
            board: components["schemas"]["ExamBoard"];
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Difficulty Level
             * @default Advanced Placement / A-Level
             */
            difficulty_level: string;
            /**
             * Icon Name
             * @default BookOpen
             */
            icon_name: string;
            /**
             * Total Duration Minutes
             * @default 180
             */
            total_duration_minutes: number;
            /**
             * Passing Score Percentage
             * @default 70
             */
            passing_score_percentage: number;
            /**
             * Subjects
             * @default []
             */
            subjects: components["schemas"]["SubjectImportSchema"][];
        };
        /** ExamTemplateResponse */
        ExamTemplateResponse: {
            /** Title */
            title: string;
            /** Code */
            code: string;
            /** @default Cambridge International */
            board: components["schemas"]["ExamBoard"];
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Difficulty Level
             * @default Advanced Placement / A-Level
             */
            difficulty_level: string;
            /**
             * Icon Name
             * @default BookOpen
             */
            icon_name: string;
            /**
             * Total Duration Minutes
             * @default 180
             */
            total_duration_minutes: number;
            /**
             * Passing Score Percentage
             * @default 70
             */
            passing_score_percentage: number;
            /** Id */
            id: string;
            /**
             * Subject Count
             * @default 0
             */
            subject_count: number;
            /**
             * Topic Count
             * @default 0
             */
            topic_count: number;
            /**
             * Objective Count
             * @default 0
             */
            objective_count: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LearningObjectiveImportSchema */
        LearningObjectiveImportSchema: {
            /**
             * Code
             * @description Unique syllabus code, e.g., '9702.4.1'
             */
            code: string;
            /**
             * Description
             * @description Competency statement
             */
            description: string;
            /**
             * Formula Latex
             * @description LaTeX formula if applicable
             */
            formula_latex?: string | null;
            /** @default Understand */
            bloom_level: components["schemas"]["BloomLevel"];
        };
        /** LearningObjectiveResponse */
        LearningObjectiveResponse: {
            /**
             * Code
             * @description Unique syllabus code, e.g., '9702.4.1'
             */
            code: string;
            /**
             * Description
             * @description Competency statement
             */
            description: string;
            /**
             * Formula Latex
             * @description LaTeX formula if applicable
             */
            formula_latex?: string | null;
            /** @default Understand */
            bloom_level: components["schemas"]["BloomLevel"];
            /** Id */
            id: string;
            /** Topic Id */
            topic_id: string;
            /** Subtopic Id */
            subtopic_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LearningPathNodeResponse */
        LearningPathNodeResponse: {
            /** Sequence Number */
            sequence_number: number;
            /** Topic Id */
            topic_id: string;
            /** Title */
            title: string;
            /** Subject Id */
            subject_id: string;
            /** Difficulty */
            difficulty: string;
            /** Estimated Hours */
            estimated_hours: number;
            /** Level */
            level: number;
            /**
             * Prerequisite Ids
             * @default []
             */
            prerequisite_ids: string[];
        };
        /** LearningPathResponse */
        LearningPathResponse: {
            /** Exam Template Id */
            exam_template_id: string;
            /** Exam Title */
            exam_title: string;
            /** Total Topics */
            total_topics: number;
            /**
             * Learning Path
             * @default []
             */
            learning_path: components["schemas"]["LearningPathNodeResponse"][];
        };
        /**
         * LearningState
         * @description Formal Student Learning States conforming to PRD §13 & FR-001.
         *     Controls the pedagogical progression lifecycle.
         * @enum {string}
         */
        LearningState: "not_started" | "calibration" | "foundation" | "practicing" | "assessment" | "diagnosis" | "repair" | "mastery" | "revision";
        /** SectionImportSchema */
        SectionImportSchema: {
            /** Title */
            title: string;
            /**
             * Order
             * @default 0
             */
            order: number;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /**
         * StateTransitionLogResponse
         * @description Public response schema for immutable audit log records.
         */
        StateTransitionLogResponse: {
            /** Id */
            id: string;
            /** Student Id */
            student_id: string;
            /** Exam Template Id */
            exam_template_id: string;
            /** Topic Id */
            topic_id: string;
            from_state: components["schemas"]["LearningState"];
            to_state: components["schemas"]["LearningState"];
            /** Trigger */
            trigger: string;
            /** Evidence Payload */
            evidence_payload: {
                [key: string]: unknown;
            };
            /** Actor Id */
            actor_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * StateTransitionRequest
         * @description Request payload for executing a verified learning state transition.
         */
        StateTransitionRequest: {
            /**
             * Exam Template Id
             * @description Target exam template UUID
             */
            exam_template_id: string;
            /**
             * Topic Id
             * @description Target syllabus topic UUID
             */
            topic_id: string;
            /** @description Desired target state in the FSM */
            target_state: components["schemas"]["LearningState"];
            /**
             * Trigger
             * @description Event reason (e.g. ASSESSMENT_PASSED, SOCRATIC_REPAIR_COMPLETE)
             */
            trigger: string;
            /**
             * Evidence Payload
             * @description Structured verification data (scores, failed items, misconception tags)
             */
            evidence_payload?: {
                [key: string]: unknown;
            };
            /**
             * Mastery Score
             * @description Optional updated mastery probability score
             */
            mastery_score?: number | null;
            /**
             * Student Id
             * @description Target student UUID (restricted to admin roles; defaults to current authenticated student)
             */
            student_id?: string | null;
        };
        /**
         * StudentLearningStateResponse
         * @description Public response schema for student topic learning state.
         */
        StudentLearningStateResponse: {
            /** Id */
            id: string;
            /** Student Id */
            student_id: string;
            /** Exam Template Id */
            exam_template_id: string;
            /** Topic Id */
            topic_id: string;
            current_state: components["schemas"]["LearningState"];
            /** Mastery Score */
            mastery_score: number;
            /** Consecutive Successes */
            consecutive_successes: number;
            /** Consecutive Failures */
            consecutive_failures: number;
            /**
             * Last Transition At
             * Format: date-time
             */
            last_transition_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SubjectDetailResponse */
        SubjectDetailResponse: {
            /** Title */
            title: string;
            /**
             * Order
             * @default 0
             */
            order: number;
            /**
             * Description
             * @default
             */
            description: string;
            /** Id */
            id: string;
            /** Exam Template Id */
            exam_template_id: string;
            /**
             * Topics
             * @default []
             */
            topics: components["schemas"]["TopicDetailResponse"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SubjectImportSchema */
        SubjectImportSchema: {
            /** Title */
            title: string;
            /**
             * Order
             * @default 0
             */
            order: number;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Sections
             * @default []
             */
            sections: components["schemas"]["SectionImportSchema"][];
            /**
             * Topics
             * @default []
             */
            topics: components["schemas"]["TopicImportSchema"][];
        };
        /** SubtopicImportSchema */
        SubtopicImportSchema: {
            /** Title */
            title: string;
            /**
             * Order
             * @default 0
             */
            order: number;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** SubtopicResponse */
        SubtopicResponse: {
            /** Id */
            id: string;
            /** Topic Id */
            topic_id: string;
            /** Title */
            title: string;
            /** Order */
            order: number;
            /** Description */
            description: string;
        };
        /**
         * TokenResponse
         * @description OAuth2 Bearer token response.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserResponse"];
        };
        /** TopicBlockerReportResponse */
        TopicBlockerReportResponse: {
            /** Target Topic Id */
            target_topic_id: string;
            /** Target Topic Title */
            target_topic_title: string;
            /** Exam Template Id */
            exam_template_id: string;
            /** Student Id */
            student_id: string;
            /** Is Unlocked */
            is_unlocked: boolean;
            /** Total Unmastered Ancestors */
            total_unmastered_ancestors: number;
            /**
             * Blockers
             * @default []
             */
            blockers: components["schemas"]["BlockerNodeResponse"][];
        };
        /** TopicDetailResponse */
        TopicDetailResponse: {
            /** Title */
            title: string;
            /**
             * Order
             * @default 0
             */
            order: number;
            /** @default intermediate */
            difficulty: components["schemas"]["TopicDifficulty"];
            /**
             * Estimated Hours
             * @default 4
             */
            estimated_hours: number;
            /**
             * Importance Weight
             * @default 1
             */
            importance_weight: number;
            /**
             * Description
             * @default
             */
            description: string;
            /** Id */
            id: string;
            /** Subject Id */
            subject_id: string;
            /** Section Id */
            section_id?: string | null;
            /**
             * Subtopics
             * @default []
             */
            subtopics: components["schemas"]["SubtopicResponse"][];
            /**
             * Objectives
             * @default []
             */
            objectives: components["schemas"]["LearningObjectiveResponse"][];
            /**
             * Prerequisites
             * @default []
             */
            prerequisites: components["schemas"]["TopicPrerequisiteResponse"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TopicDifficulty
         * @enum {string}
         */
        TopicDifficulty: "foundational" | "intermediate" | "advanced";
        /** TopicImportSchema */
        TopicImportSchema: {
            /** Title */
            title: string;
            /**
             * Order
             * @default 0
             */
            order: number;
            /** @default intermediate */
            difficulty: components["schemas"]["TopicDifficulty"];
            /**
             * Estimated Hours
             * @default 4
             */
            estimated_hours: number;
            /**
             * Importance Weight
             * @default 1
             */
            importance_weight: number;
            /**
             * Description
             * @default
             */
            description: string;
            /** Code */
            code?: string | null;
            /**
             * Subtopics
             * @default []
             */
            subtopics: components["schemas"]["SubtopicImportSchema"][];
            /**
             * Objectives
             * @default []
             */
            objectives: components["schemas"]["LearningObjectiveImportSchema"][];
            /**
             * Prerequisites
             * @default []
             */
            prerequisites: components["schemas"]["TopicPrerequisiteImportSchema"][];
        };
        /** TopicPrerequisiteImportSchema */
        TopicPrerequisiteImportSchema: {
            /** Prerequisite Topic Code Or Title */
            prerequisite_topic_code_or_title: string;
            /**
             * Is Mandatory
             * @default true
             */
            is_mandatory: boolean;
        };
        /** TopicPrerequisiteResponse */
        TopicPrerequisiteResponse: {
            /** Id */
            id: string;
            /** Topic Id */
            topic_id: string;
            /** Prerequisite Topic Id */
            prerequisite_topic_id: string;
            /** Prerequisite Topic Title */
            prerequisite_topic_title?: string | null;
            /**
             * Is Mandatory
             * @default true
             */
            is_mandatory: boolean;
        };
        /** TopicUnlockStatusResponse */
        TopicUnlockStatusResponse: {
            /** Topic Id */
            topic_id: string;
            /** Title */
            title: string;
            /** Subject Id */
            subject_id: string;
            /** Difficulty */
            difficulty: string;
            /** Level */
            level: number;
            /** Current Learning State */
            current_learning_state: string;
            /** Unlock Status */
            unlock_status: string;
            /** Is Unlocked */
            is_unlocked: boolean;
            /**
             * Missing Prerequisite Ids
             * @default []
             */
            missing_prerequisite_ids: string[];
            /**
             * Missing Prerequisite Titles
             * @default []
             */
            missing_prerequisite_titles: string[];
        };
        /**
         * UserCreate
         * @description Registration request payload.
         */
        UserCreate: {
            /** Email */
            email: string;
            /**
             * Password
             * @description Minimum 8 characters
             */
            password: string;
            /**
             * Full Name
             * @default
             */
            full_name: string;
            /** @default student */
            role: components["schemas"]["UserRole"];
        };
        /**
         * UserLogin
         * @description Login request payload.
         */
        UserLogin: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * UserResponse
         * @description Public user profile response (excludes hashed_password).
         */
        UserResponse: {
            /** Email */
            email: string;
            /**
             * Full Name
             * @default
             */
            full_name: string;
            /** @default student */
            role: components["schemas"]["UserRole"];
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UserRole
         * @description NIST-aligned Role-Based Access Control (RBAC) roles.
         *     Enforced strictly server-side (PRD FR-021, NFR-005, Non-Negotiable Constraint #6).
         * @enum {string}
         */
        UserRole: "student" | "instructor" | "admin";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_check_api_v1_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    instructor_only_check_api_v1_auth_instructor_only_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    transition_learning_state_api_v1_learning_state_transition_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StateTransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentLearningStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_topic_state_api_v1_learning_state_topic__topic_id__get: {
        parameters: {
            query: {
                /** @description Exam template UUID */
                exam_template_id: string;
                /** @description Optional student ID for instructor/admin lookup */
                student_id?: string | null;
            };
            header?: never;
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentLearningStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_topic_history_api_v1_learning_state_topic__topic_id__history_get: {
        parameters: {
            query: {
                /** @description Exam template UUID */
                exam_template_id: string;
                /** @description Optional student ID for instructor/admin lookup */
                student_id?: string | null;
            };
            header?: never;
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateTransitionLogResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exam_summary_api_v1_learning_state_exam__exam_template_id__get: {
        parameters: {
            query?: {
                /** @description Optional student ID for instructor/admin lookup */
                student_id?: string | null;
            };
            header?: never;
            path: {
                exam_template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamLearningSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exam_templates_api_v1_exam_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamTemplateResponse"][];
                };
            };
        };
    };
    get_exam_template_api_v1_exam_templates__template_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamTemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_exam_template_api_v1_exam_templates__template_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_syllabus_tree_api_v1_exam_templates__template_id__syllabus_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectDetailResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_topic_detail_api_v1_exam_templates_topics__topic_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_exam_blueprint_api_v1_exam_templates_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamTemplateImportSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamTemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exam_dag_api_v1_exam_templates__template_id__dag_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DAGGraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_learning_path_api_v1_exam_templates__template_id__learning_path_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningPathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_unlocked_topics_api_v1_exam_templates__template_id__unlocked_topics_get: {
        parameters: {
            query?: {
                student_id?: string | null;
            };
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicUnlockStatusResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_topic_prerequisite_blockers_api_v1_exam_templates__template_id__topics__topic_id__blockers_get: {
        parameters: {
            query?: {
                student_id?: string | null;
            };
            header?: never;
            path: {
                template_id: string;
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicBlockerReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_exam_dag_api_v1_exam_templates__template_id__validate_dag_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DAGValidationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
